### ISSUE TITLE
snclient doenst start after upgrade from 0.19 to 0.20 on el8

### ISSUE THREAD

**Issue by ccztux** [ConSol-Monitoring/snclient#103]
I have upgraded snclient from version `0.19` to `0.20` on my `el8` test system and the service doesnt start after that.

strace output:
```
root@localhost ~ # strace -a 80 -s 120 -f /usr/bin/snclient --config=/etc/snclient/snclient.ini
execve("/usr/bin/snclient", ["/usr/bin/snclient", "--config=/etc/snclient/snclient.ini"], 0x7ffc2bb48b80 /* 187 vars */) = -1 ENOEXEC (Exec format error)
strace: exec: Exec format error
+++ exited with 1 +++
```

**Comment by sni** [comment]
Sounds like you installed the arm version on x86 or the other way round.

Does this look similar on your system?
```
%> file /usr/bin/snclient 
/usr/bin/snclient: ELF 64-bit LSB executable, x86-64, ...

%> uname -m
x86_64
```

**Comment by ccztux** [comment]
You are right, sorry for that!

**Comment by sni** [comment]
no worries, those filenames were really confusing with only one letter difference in `amd64` and `arm64`. Next release will have less confusing names and will use `x86_64` and `aarch64` in the release files.
