### ISSUE TITLE
check_drivesize: disk usage is shown as own drive

### ISSUE THREAD

**Issue by teanva** [ConSol-Monitoring/snclient#109]
Check_drivesize shows two drives although there is only one.

![image](https://github.com/ConSol-Monitoring/snclient/assets/117991310/57df6b28-c782-48de-93be-f22a5a217f40)

Command line:

-c check_drivesize
OK - All 2 drive(s) are ok |'C:\ used'=16275165184B;128763451802;144858883277;0;160954314752 'C:\ used %'=10.1%;80;90;0;100 ' used'=34463744B;83882803;94368154;0;104853504 ' used %'=32.9%;80;90;0;100

-c check_drivesize drive=C
OK - All 2 drive(s) are ok |'C:\ used'=16279162880B;128763451802;144858883277;0;160954314752 'C:\ used %'=10.1%;80;90;0;100 ' used'=34463744B;83882803;94368154;0;104853504 ' used %'=32.9%;80;90;0;100

-c check_drivesize drive=C:
OK - All 2 drive(s) are ok |'C:\ used'=16279162880B;128763451802;144858883277;0;160954314752 'C:\ used %'=10.1%;80;90;0;100 ' used'=34463744B;83882803;94368154;0;104853504 ' used %'=32.9%;80;90;0;100

snclient: v0.22
check_nrpe: v4.1.0

**Comment by Gent00157** [comment]
Hi,
I tried and I can confirm that. In my case I get an extra info about "System Reserved" partition. if I configure alias in the ini file, then and execute it, then it is working correctly.
In your case it might be EFI partition (according to size) - can you check disk management and confirm it please?

**Comment by sni** [comment]
You could also try the latest nightly build, i recently fixed detecting mounted volumes on windows with https://github.com/ConSol-Monitoring/snclient/commit/2759c2f0f2a8b9dd3604d041354d903a5d3db9da

**Comment by teanva** [comment]
I tested with v0.22.0011 but no change.

Second drive seems to be boot partition:

![Partitions](https://github.com/ConSol-Monitoring/snclient/assets/117991310/b39aecfc-0b46-4602-8a72-39403a220a61)

**Comment by sni** [comment]
could you try the latest nightly again, i change a few things again with
6e513fe7107c562bf1872541c3b17ca245c64475

**Comment by teanva** [comment]
Thanks, v0.22.0012 fixed the problem:

![DiskStatus](https://github.com/ConSol-Monitoring/snclient/assets/117991310/3f6732cd-ad47-4384-8c07-cc21464dce24)

**Comment by sni** [comment]
thanks for the feedback
