### ISSUE TITLE
check_os_updates improvement

### ISSUE THREAD

**Issue by Saevar2000** [ConSol-Monitoring/snclient#116]
Can you add logic to check_os_updates (or maybe create a new one check_os_eol?) that detects when OS end-of-life date is and return warning/critical with message when the end-of-life date is if it is in x many days.

https://endoflife.date/docs/api has all the end-of-life dates needed. What do you think?

**Comment by sni** [comment]
Sounds helpful, would you want to take a look at that check?

**Comment by Saevar2000** [comment]
I can make an attempt (I have never programmed in go before), if you don't have time.

**Comment by sni** [comment]
closing this one, i'd say snclient is the wrong place for a eol check.
