### ISSUE TITLE
check process with template syntax

### ISSUE THREAD

**Issue by kafos** [ConSol-Monitoring/snclient#126]
I tried the template syntax with a check_process of VNC processes but it seems that the conditioning does not work properly:

command: check_nsc_web -k -p "PASSWORD" -u https://IP:PORT  \
check_process process=tvnserver.exe warn="state=stoppped || count > 1 || count < 1" \
ok-syntax="%(status) - VNC running" 'empty-state=3' \
'top-syntax=%(status) - %(count) - {{ IF count > 1 }} "active VNC session" {{ ELSIF count < 1 }} "VNC OK" {{ END }}'

the output looks like this:
WARNING - 2 -  "active VNC session"  "VNC OK" |'count'=2;1:1;;0; 'rss'=77619200B;;;0; 'virtual'=9033150464B;;;0; 'cpu'=28.791498%;;;0;

documentation says:
{{ IF <expression> }}...{{ ELSIF <expression> }}...{{ ELSE }}...{{ END }}
"ELSIF" correct? -- anyway -tried with ELSEIF or ELIF - dont' get the correct output.

Tried it also with  {{ IF %(count) > 1 }} "active VNC session" {{ ELSIF %(count) < 1 }}

**Comment by sni** [comment]
i cannot reproduce this, which snclient version is this?

**Comment by kafos** [comment]
It's version 0.25
here some screenshots:
![image](https://github.com/ConSol-Monitoring/snclient/assets/29919422/0c6eebde-3b18-4d20-ae15-f13fc2785416)

![image](https://github.com/ConSol-Monitoring/snclient/assets/29919422/ef1a24f4-3e46-408d-8d74-dc94bb5f7502)

![image](https://github.com/ConSol-Monitoring/snclient/assets/29919422/a157a759-ee7b-4d40-aac8-059dfa0872ba)

**Comment by sni** [comment]
so it does work now?

**Comment by kafos** [comment]
the value count is 2 and based on
"top-syntax=%(status) - %(count) - {{ IF %(count) < 1 }} NO VNC PROCESS RUNNING {{ ELSIF %(count) > 1 }} RUNNING SESSION {{ END }}"
the output should be "WARNING - 2 - RUNNING SESSION"

Seems that "IF %(count) < 1" gives TRUE back but it's FALSE.

**Comment by sni** [comment]
could you try `{{ IF count < 1 }}` the %() are not required in the if expression

**Comment by sni** [comment]
finally found the issue, thanks for reporting this. Should be fine with the next release.
