### ISSUE TITLE
Check_OS_Version in 0.25 not pulling OS Build Number

### ISSUE THREAD

**Issue by q2uantum** [ConSol-Monitoring/snclient#134]
Previous to 0.25 - we would get the following when doing Check_OS_Version:

OK - Microsoft Windows Server 2019 Standard 10.0.17763.6054 Build 17763.6054 (arch: amd64)

0.25 now reports back this:

OK - Microsoft Windows Server 2019 Standard (arch: amd64)

Build version is useful to us and is used when doing checks on servers to see if they are fully patched with updates, as build number changes when patched.

Using SNLCIENT with Nagios Core 4.5.3

**Comment by alexoalexo** [comment]
I've just noticed the same, right after upgrading today.

**Comment by sni** [comment]
reported upstream:
https://github.com/shirou/gopsutil/issues/1666#issuecomment-2222538893

**Comment by davidnewhall** [comment]
No you didn't. Someone asked for a feature in Linux, and you left a comment about Windows that doesn't even make sense. That wasn't a report by any means.

**Comment by davidnewhall** [comment]
https://github.com/shirou/gopsutil/pull/1629
