### ISSUE TITLE
No PerfData for check_drivesize when using warn and crit other than used_pct

### ISSUE THREAD

**Issue by Stefan-Hoesl** [ConSol-Monitoring/snclient#136]
Hello,

I am monitoring Linux und Windows server with check_nsc_web. When calling check_drivsize with the default parameters
performance data ist returned.
If I use used_pct for for warn and crit the perfomance data is also returned.
If I us any other filters than used_pct, no performance data is returned.

**Comment by sni** [comment]
thanks for reporting this, should be fine now.
