### ISSUE TITLE
check_drivesize - case sensitivity on Linux box

### ISSUE THREAD

**Issue by jframeau** [ConSol-Monitoring/snclient#14]
When checking for /home (but any directory failed in fact but /), I get:

**All 0 drive(s) are ok**

I think this part of code is wrong:

for _, arg := range argList {
		switch arg.key {
		case "drive":
			drives = append(drives, **strings.Split(strings.ToUpper(arg.value)**, ",")...)
		case "exclude":
			excludes = append(excludes, **strings.Split(strings.ToUpper(arg.value)**, ",")...)
		}
	}
 
as gopsutil returns current case.

jfr

**Comment by sni** [comment]
The linux drivesize check is not yet completed, i added table here:
https://github.com/ConSol-Monitoring/snclient#implementation-status

**Comment by sni** [comment]
should be better now.
