### ISSUE TITLE
Transcript is being written for every Powershell script call

### ISSUE THREAD

**Issue by h4ppywastaken** [ConSol-Monitoring/snclient#140]
When running a custom ps1 check script with check_nrpe using the snclient wrapper command a transcript gets saved in snclient folder everytime.

## Expected Behavior
No Transcript should be written.

## Current Behavior
Every ps1 call through snclient wrapper writes transcript. (did not test without wrapper command)

## Context (Environment)
Monitoring Host: OMD stack with naemon core
snClient Version: 0.26 Windows

## Detailed Description
Every call of a powershell script through the wrapper command leads to a transcript being saved to %snclientroot%/YYYYMMDD/PowerShell_transcript.%SERVERNAME%.%SOMEHASH%.

**Comment by sni** [comment]
do you know how to disable it? Did a quick search and it seems like this is a group policy, so something out of control of snclient.
Also i don't see that behavior in the lab.

**Comment by h4ppywastaken** [comment]
This issue is being resolved - the GPO setting "Computer Configuration – Administrative Templates – Windows Components –  Windows PowerShell - Turn on PowerShell Transcription" was enabled. Thank you for the quick response!
