### ISSUE TITLE
SN-Client Service Not Being Created Upon Installation On Windows

### ISSUE THREAD

**Issue by muhammadkashanzafar** [ConSol-Monitoring/snclient#145]
Hi,
I have built snclient from the source and successfully generated the msi setup for windows installation. Using msi setup, I was able to install the snclient but there was not snclient service and also was not able to access the web portal where it should the running status for snclient. I have followed the official documentation for this entire process. 
I have been stuck in this issue for last two days now and would really appreciate some help.  Thank you in advance.

**Version:**
0.26.0033

**Command to Create the MSI Setup:**
& .\packaging\windows\build_msi.ps1 `
-out "snclient.msi" `
-arch "amd64" `
-major "0" `
-minor "26" `
-rev "33" `
-sha "1469f48"

Best Regards,

**Comment by muhammadkashanzafar** [comment]
Issue has been resolved

**Comment by sni** [comment]
just a small note, snclient does not come with a web interface. Only a REST API to run checks and some administrative tasks.
