### ISSUE TITLE
What does it mean ? "Unknown Error in Script: %!s(<nil>)"

### ISSUE THREAD

**Issue by firatalkis** [ConSol-Monitoring/snclient#17]
Hello,

I am trying this new monitoring agent for replacement nsclient++. But I got this error "Unknown Error in Script: %!s(<nil>)".

Which I wrong things? Could you please check my snclient.ini file at the attachment?

![image](https://github.com/ConSol-Monitoring/snclient/assets/42132281/7515e48c-9de4-49df-82f6-ac0c05ad02b9)

![image](https://github.com/ConSol-Monitoring/snclient/assets/42132281/525cf618-c913-4519-875b-ccde911e934e)

[snclient_ini.txt](https://github.com/ConSol-Monitoring/snclient/files/11870143/snclient_ini.txt)

Thanks.

**Comment by sni** [comment]
should be fine since f4a0ca3e79f5a6a95b9d1b634dba551feb2cb5f2
Could you try the latest nightly build?

**Comment by firatalkis** [comment]
when will build it as exe?

**Comment by firatalkis** [comment]
yes this worked, thanks
