### ISSUE TITLE
Uptime checks not working.

### ISSUE THREAD

**Issue by feathers1664** [ConSol-Monitoring/snclient#174]
Using check_nrpe;

$ /usr/local/nagios/libexec/check_nrpe -t 120 -H 10.10.10.1 -p 5667 -t 60 -c check_uptime -a 'warn=uptime < 20M' 
CRITICAL - uptime: 26m, boot: 2024-11-15 05:39:16 (UTC) |'uptime'=1590s;0:;86400:

$ /usr/local/nagios/libexec/check_nrpe -t 120 -H 10.10.10.1 -p 5667 -t 60 -c check_uptime -a 'crit=uptime < 20M' 
WARNING - uptime: 26m, boot: 2024-11-15 05:39:16 (UTC) |'uptime'=1601s;172800:;0:

/usr/local/nagios/libexec/check_nrpe -t 120 -H 10.10.10.1 -p 5667 -t 60 -c check_uptime -a 'warn=uptime < 20M'  'crit=uptime < 15M' 
OK - uptime: 27m, boot: 2024-11-15 05:39:16 (UTC) |'uptime'=1675s;0:;0:

**Comment by sni** [comment]
have you tried lowercase `m` for minutes?

**Comment by feathers1664** [comment]
-face palm-

Yeah, that works.
