### ISSUE TITLE
check_nrpe UNKNOWN on status message "OK"

### ISSUE THREAD

**Issue by h4ppywastaken** [ConSol-Monitoring/snclient#19]
When running i.e. CPU check with check_nrpe the check plugin returns with status text "OK..." but the exit code is 3 which results in UNKNOWN. This happens on other check_nrpe checks too, not only on CPU check.
![grafik](https://github.com/ConSol-Monitoring/snclient/assets/25606631/aa66f711-5ced-4918-89cd-cac2373ee86a)
![grafik](https://github.com/ConSol-Monitoring/snclient/assets/25606631/0d7f7d8b-fc38-4ce7-b88d-c0907a62e3af)

## Expected Behavior
check_nrpe should return with exit status 0 and status text "OK..."

## Current Behavior
check_nrpe returns with exit status 3 and status text "OK..."

## Context (Environment)
Monitoring Host: OMD stack with naemon core
check_nrpe Plugin for Nagios Version: 4.1.0
snClient Version: 0.3 Windows

## Detailed Description
Check Command: check_nrpe -H xxx -2 -c check_cpu -a 'warn=load>90' 'crit=load>95' time=1m time=10m time=30m
The same command works when running NSClient++ on the Windows machine.

**Comment by sni** [comment]
thanks for reporting this, must have something to do with the nrpe transport. All checks via nrpe report exit code 3 while it works with check_nsc_web. Will have a look...

**Comment by sni** [comment]
fixed in ae7e3f648890440873f9fab4b76c407acc99e20a

thanks for your report
