### ISSUE TITLE
new "regexpi" filter for matching processes/services case insensitive

### ISSUE THREAD

**Issue by lgmu** [ConSol-Monitoring/snclient#20]
for example:
check_process "filter=exe regexp "WES.*" 

-> in nsclient this is always case sensitive

Would be great to be able to do something like this:
/wes.*/i or "regexpi"

For users I think "regexpi" would be easier to use :)

**Comment by sni** [comment]
both ways are possible now, see https://github.com/ConSol-Monitoring/snclient/blob/main/docs/filter/_index.md
