### ISSUE TITLE
check_nrpe custom check script "not a valid Win32 application"

### ISSUE THREAD

**Issue by h4ppywastaken** [ConSol-Monitoring/snclient#22]
When running a custom check script with check_nrpe it throws status "UNKNOWN" with "...%1 is not a valid Win32 application."
![grafik](https://github.com/ConSol-Monitoring/snclient/assets/25606631/3e30d071-8e20-4829-a387-40d4540427e6)

## Expected Behavior
check_nrpe should return with exit status 0 and status text "OK..."

## Current Behavior
check_nrpe returns with exit status 3 and status text "...%1 is not a valid Win32 application."

## Context (Environment)
Monitoring Host: OMD stack with naemon core
check_nrpe Plugin for Nagios Version: 4.1.0
snClient Version: 0.04 Windows

## Detailed Description
snclient.ini:
![grafik](https://github.com/ConSol-Monitoring/snclient/assets/25606631/a0052cfe-220c-4278-9ff7-9e62c70441f9)
The script does not need any arguments to run.

The exact same script and configuration worked on snClient version 0.03 and stopped working directly after I installed version 0.04.
![grafik](https://github.com/ConSol-Monitoring/snclient/assets/25606631/3dd8ba1c-45a7-497e-82b5-18e172440455)

**Comment by sni** [comment]
previously the 0.03 started all external scripts with a powershell, the 0.04 calls os.exec on them, like the nsclient did. So if you want to run it with powershell, you need to add powershell to the command or add it as wrapped script
