### ISSUE TITLE
installation on Mac OSX fails

### ISSUE THREAD

**Issue by airathere** [ConSol-Monitoring/snclient#27]
Hi,
first of: thanks for your great effort to have a new and supported client again!!

i tried to install it on my Macbook M2 Pro, OS 13.4.1(c) with your osx-arm64.pkg package.
it fails with "this package is not compatible with this mac os-version"?!

**Comment by sni** [comment]
The github runner builds the packages with osx 12. I don't have access to a M2, so i am unable to test this.
Does it work if you build the pkg manually? See:
https://github.com/ConSol-Monitoring/snclient/blob/main/docs/install.md#building-osx-pkg
Let me know if the installation instructions can be improved, so far they are pretty basic.

**Comment by airathere** [comment]
build the package successfully as described but the new .pkg file results with the same installation error

**Comment by sni** [comment]
thanks for your report, should be fine now. Seems like packages are not allowed now to install man pages into /usr/share/man, so we install them in /usr/local/share/man now.
