### ISSUE TITLE
Add folder size support

### ISSUE THREAD

**Issue by lgmu** [ConSol-Monitoring/snclient#38]
Would be great if either **check_files** had a mode to check the size of folders or if there was a **check_folder**.
Right now it's only possible to check the size of individual files in the folder, but not the whole folder itself.

In Powershell this can be achieved like this:
$foldersize = (Get-ChildItem -Path "$folder" -Recurse | Measure-Object -Property Length -Sum).Sum

**Comment by airathere** [comment]
@lmgu: sorry to say that: no.
imho get-childitem is really not helpful nor working in middle to large sized folders in any way, see also: https://devblogs.microsoft.com/powershell/why-is-get-childitem-so-slow/
If you need to read folder sizes you have to use other possibilities

**Comment by lgmu** [comment]
> One day, you’ll install a build and the issues will just magically be gone.
This article is from 2009 and I have no issues whatsoever with 20+ GB Folders.

 And it was just an example. In Go this would be implemented entirely different anyway.

**Comment by sni** [comment]
check_files now shows the total size along with some performance data. It does not add additional overhead to the current code, since the agent has to stat() each file anyway already.
