### ISSUE TITLE
Parse error on non-numeric Windows version

### ISSUE THREAD

**Issue by lausser** [ConSol-Monitoring/snclient#5]
check_nsc_web -u https://127.0.0.1:18444 -p 12345 -k -t 30 check_os_version
failed to parse platform version to float: strconv.ParseFloat: parsing "**10.0.17763.4252 Build 17763.4252**": invalid syntax 

Version info is not necessary a number (or combination of numbers and dots)

The same check with NSClient++ shows:
OK: Windows Server 2016 Technical Preview (10.0.17763) |'version'=100;50;50;;

Although it has a performance metric, it does not look very useful.
I suggest not to output any perfdata here.

**Comment by sni** [comment]
fixed in 4aceeacaf4213a748cf64e87262240c1a48db3c5
