### ISSUE TITLE
Defaults Arguments values

### ISSUE THREAD

**Issue by FranckSallet** [ConSol-Monitoring/snclient#53]
Hi,

thank you for this great project, especially for windows sysadmins that needs a new naemon client with new features.

is there a way to overwrite defaults parameters of built-in checks ?

regards

**Comment by FranckSallet** [comment]
Ultimately, find my response here by using command alias

**Comment by sni** [comment]
Right, an alias should do the trick. But might be a nice idea to make them a config option when anyone finds some time.
