### ISSUE TITLE
Windows's service not created anymore with the installer

### ISSUE THREAD

**Issue by BenoitPoulet** [ConSol-Monitoring/snclient#62]
Hello,

Just to let you know that with : snclient-0.13-windows-amd64.msi

The Windows's service not created anymore.

Os from the cmd line of SNclient : 
SNClient+ starting (version:v0.13. - build:34e213b - host:piwv-monitoring-02 - pid:6524 - os:Microsoft Windows Server 2019 Standard 10.0.17763.4851 Build 17763.4851 - arch:amd64)

Regards.

**Comment by sni** [comment]
Is this a new installation or an update? The way, the services gets installed changed. It is no longer installed from the msi itself, but from a post hook during the installation.
Is there anything the logfile regarding the service?

**Comment by BenoitPoulet** [comment]
Hello,
Sorry for my late reply.

I reset my install and everything is ok.

Sorry for the noise.
