### ISSUE TITLE
check_network - metrics

### ISSUE THREAD

**Issue by jframeau** [ConSol-Monitoring/snclient#77]
check_network gives in/out bandwith as ouput.

But metrics are in bytes and associated graphes (say Grafana) are in bytes consequently.

Ex:
Name 	Value 	
enp1s0_traffic_in 	737,073,236c 	
enp1s0_traffic_out 	141,201,248c

![image](https://github.com/ConSol-Monitoring/snclient/assets/498115/9051f16a-1951-4181-8e6c-0e3b5bcc1e4f)

Wouldn't be  preferable to get bandwith directly as metrics ?

jfr

**Comment by sni** [comment]
Raw data is always better. You graphing tool can then easily calculate a rate from that. That's way there it shows the "c / counter" unit. Some graphing tools automatically use a rate function then.

**Comment by jframeau** [comment]
hmm, this is from stock omd 5.21 + grafana.

I just discovered Derivative function with Grafana, which should be the
right way to get traffic rates.

So I imagine now that I need an histou template to set performance graphs
as needed.

Le ven. 5 janv. 2024 à 18:26, Sven Nierlein ***@***.***> a
écrit :

**Comment by sni** [comment]
i'll have a look, histou should recognize the counter automatically and apply a rate function.

**Comment by sni** [comment]
should be fine with tomorrows nightly. I fixed the histou template to support counters as well.

**Comment by jframeau** [comment]
OMD 5.21~2024-01-11

**check_nwc - traffic**

![image](https://github.com/ConSol-Monitoring/snclient/assets/498115/6e92d9a2-ce67-491d-ad96-d4287379974f)

**snclient -traffic**

![image](https://github.com/ConSol-Monitoring/snclient/assets/498115/de56eaaa-99f1-4be6-a7d8-e1a32edc312a)

**what I would like to see :-) check_nwc or nclient - traffic in bit/s**

![image](https://github.com/ConSol-Monitoring/snclient/assets/498115/81c7543d-d968-4a23-bb58-3e5e0bb1ab15)

The last in not based on Difference but on Derivative function form InfluxDB, with a math applied so bytes are converted as bit.

I wonder if it could be interesting to add a type of panel based on derivative so one could compute rates.

InfluxDB select: derivative(mean("value"), 1s) * 8

**Comment by sni** [comment]
You are right, difference() is wrong here, switching to non_negative_derivative("1s").
Besides that, if you are not happy with the default template, you can also copy it into the local folder and adjust it to your needs or even create a total custom one.
