### ISSUE TITLE
add support for multiple "allowed hosts" definitions to improve readability

### ISSUE THREAD

**Issue by lgmu** [ConSol-Monitoring/snclient#78]
For example:

```
# ABC
allowed hosts = 10.0.0.1,10.0.0.2
# DEF
allowed hosts += 10.0.0.3,10.0.0.4
```

Currently there is no "+=" Syntax and you can only override it

**Comment by sni** [comment]
this is possible now, just make sure you add commas where you want them. The config lines will simply be joined as text.
See an example here:
https://github.com/ConSol-Monitoring/snclient/blob/main/docs/configuration/index.md#appending-values
