### ISSUE TITLE
check_service exclude docs

### ISSUE THREAD

**Issue by zGLados** [ConSol-Monitoring/snclient#87]
Hello,

I started using check_service to check all services in autostart on my Windows server.
Services like edgeupdate, RemoteRegistry and sppsvc for example, are marked as automatic start and don't run all the time, so I want to exclude that service.

So when I do the check_service, I get the output:
`WARNING - , delayed (warning(edgeupdate=stopped (delayed), RemoteRegistry=stopped (delayed), sppsvc=stopped (delayed))) |'count'=214;;;0; 'failed'=3;;;0;`

I found the `exclude` argument in the docs, so if I want to exclude the services I mentioned before (edgeupdate, RemoteRegistry and sppsvc) I have to do it like that:
`check_service exclude=edgeupdate exclude=RemoteRegistry exclude=sppsvc`
This gives me the Output I want:
`OK - All 211 service(s) are ok. |'count'=211;;;0; 'failed'=0;;;0;`

Can you please add an example for this in the documentation?

**Comment by sni** [comment]
thanks for the hint, i added your example.
