### ISSUE TITLE
Service-Check Unknown output "json error: unexpected end of JSON input"

### ISSUE THREAD

**Issue by kafos** [ConSol-Monitoring/snclient#98]
I created a service-check with a command is like this:
check_nsc_web -k -p "password" -u https://10.8.0.100:8443 check_service service=SERVICNAME 'warn=state!=started'
If the service is  enabled, everything is ok. 

If I stop and disable the Service, I get:
![image](https://github.com/ConSol-Monitoring/snclient/assets/29919422/278a73ae-6587-42b1-ad6c-67a3b066f586)
Not sure but it worked before version 0.19

**Comment by kafos** [comment]
I'm currently using the newest versions of check_nsc_web (0.6.3)
The output of -vv is:
>>>>>>REQUEST:
GET /query/check_service?service=SERVICENAME&warn=state%21%3Dstarted HTTP/1.1
Host: 10.8.0.117:8443
User-Agent: Go-http-client/1.1
Password: PASSWORD
Accept-Encoding: gzip


>>>>>>
<<<<<<RESPONSE:
HTTP/1.1 200 OK
Content-Type: application/json
Date: Thu, 07 Mar 2024 20:15:34 GMT
Content-Length: 0


<<<<<<
UNKNOWN - json error: unexpected end of JSON input

**Comment by sni** [comment]
i found the issue, should be fine with the next build.
